### ISSUE TITLE
Suggestion for better management of package images

### ISSUE THREAD

**Issue by alisalehi1380** [Mohsen-mhm/laravel-image-charts#2]
Hello Dear @Mohsen-mhm 
I appreciate your efforts in the open-source community in advance. 🔥

I think it is better to manage the images in your package in this way.
https://github.com/alisalehi1380/filament-breezy/tree/2.x/art

good luck ✌️

**Comment by Mohsen-mhm** [comment]
Hello @alisalehi1380 ,

Thank you for your kind words and for your suggestion regarding image management. I appreciate your effort and the contribution you've made to the project. 🔥
